# Generated by Django 3.2.16 on 2023-01-24 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationality',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID Number')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Madam', 'Madam')], default='Mr', max_length=5, verbose_name='Title')),
                ('firstname', models.CharField(max_length=125, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=125, verbose_name='Last Name')),
                ('othername', models.CharField(blank=True, max_length=125, null=True, verbose_name='Other Name (optional)')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=9, verbose_name='Gender')),
                ('email', models.CharField(default=None, max_length=255, verbose_name='Email')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+353000000000', help_text='Enter number with Country Code Eg. +353000000000', max_length=128, region=None, verbose_name='Phone Number (Example +353000000000)')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('address', models.CharField(blank=True, help_text='address of current residence', max_length=125, null=True, verbose_name='Address')),
                ('education', models.CharField(choices=[('Masters Degree', 'Masters Degree'), ('Bachelor Degree', 'Bachelor Degree'), ('Craft / Higher Certificate', 'Craft / Higher Certificate'), ('Leaving Certificate', 'Leaving Certificate'), ('Junior Certificate', 'Junior Certificate'), ('Other', 'Other')], help_text='Highest educational level', max_length=26, null=True, verbose_name='Education')),
                ('lastwork', models.CharField(blank=True, help_text='Where was the last place you worked ?', max_length=125, null=True, verbose_name='Last Place of Work')),
                ('position', models.CharField(blank=True, help_text='What position where you in your last place of work ?', max_length=255, null=True, verbose_name='Position Held')),
                ('startdate', models.DateField(help_text='date of employement', null=True, verbose_name='Employement Date')),
                ('employeetype', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type')),
                ('dateissued', models.DateField(help_text='date staff id was issued', null=True, verbose_name='Date Issued')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRApp.department', verbose_name='Department')),
                ('nationality', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRApp.nationality', verbose_name='Nationality')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRApp.role', verbose_name='Role')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created'],
            },
        ),
    ]
