# Generated by Django 3.2.16 on 2023-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0002_bank_emergency_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='button to toggle employee block and unblock', verbose_name='Is Blocked'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='button to toggle employee deleted and undelete', verbose_name='Is Deleted'),
        ),
    ]
