# Generated by Django 3.2.16 on 2023-01-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0003_auto_20230125_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(help_text='select employee(s) to add bank account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HRApp.employee', unique=True),
        ),
    ]
