# Generated by Django 3.2.16 on 2023-01-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0005_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRApp.employee'),
        ),
    ]
