# Generated by Django 3.2.16 on 2023-01-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0008_leave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
    ]
