# Generated by Django 3.2.16 on 2023-02-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRApp', '0009_remove_leave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='foccupation',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='moccupation',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='updated',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='fullname',
            field=models.CharField(help_text='who should we contact ?', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Fiance', 'Fiance'), ('Cousin', 'Cousin'), ('Fiancee', 'Fiancee'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Son', 'Son'), ('Daughter', 'Daughter')], help_text='Who is this person to you ?', max_length=8, null=True, verbose_name='Relationship with Person'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter number with Country Code Eg. +353240000000', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter number with Country Code Eg. +353000000000', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
