# Generated by Django 3.2.16 on 2023-02-01 18:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0011_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number of Next of Kin', max_length=128, null=True, region=None, verbose_name='Next of Kin Phone Number'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='spouse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spouse (Full Name)'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Enter number with Country Code Eg. +353240000000', max_length=128, null=True, region=None, verbose_name='Spouse Phone Number'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
