# Generated by Django 3.2.16 on 2023-02-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0013_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('anual', 'Anual Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave')], max_length=25, null=True, verbose_name='Leave Type'),
        ),
    ]
